### ISSUE TITLE
Issue with rule TAF.TAF-2 

### ISSUE THREAD

**Issue by mgoberfield** [wmo-im/iwxxm#105]
According to TAF.TAF-2 error message, the following NIL TAF in XML format satisfies its condition, yet it is still flagged.

> TAF.TAF-2: A 'Nil' report should have appropriately filled elements including iwxxm:issueTime, iwxxm:aerodrome, iwxxm:validTime (missing), iwxxm:baseForecast (empty with nilReason), iwxxm:changeForecast (missing), iwxxm:previousReportAerodrome (missing) and iwxxm:previousReportValidPeriod (missing)

![nil-taf](https://user-images.githubusercontent.com/7852621/44115017-4df74332-9ffc-11e8-89fd-4ff21d4ce842.png)

**Comment by blchoy** [comment]
This is the test string:
`<sch:assert test="( if( @status = 'MISSING' and string-length(@translationFailedTAC) eq 0 ) then( exists(iwxxm:issueTime) and exists(iwxxm:aerodrome) and empty(iwxxm:validTime) and (empty(iwxxm:baseForecast/*) and iwxxm:baseForecast/@nilReason = 'http://codes.wmo.int/common/nil/missing') and empty(iwxxm:changeForecast) and empty(iwxxm:previousReportAerodrome) and empty(iwxxm:previousReportValidPeriod) ) else( true() ) )">`

I have to say that I change the schematron rule from previous version by mandating the use of `@nilReason="missing"' instead of '@nilReason="http://codes.wmo.int/common/nil/missing"` in view of #97 but haven't update the TAC-to-XML guide.  Thanks for pointing out.

**Comment by blchoy** [comment]
I am closing this and move over the discussion to #107.
