### ISSUE TITLE
MeteorologicalAerodromeReportStatus and TAFReportStatus may need to be broken into two parts

### ISSUE THREAD

**Issue by blchoy** [wmo-im/iwxxm#125]
When studying #121, it was noticed that both AMD and CNL can be present at the same time:

> TAF AMD YUDO 161500Z 1600/1618 CNL

A closer look at the template indicated that NORMAL, AMENDMENT and CORRECTION are statuses of a report while CANCELLATION and MISSING are part of or referring to the content of a report.  The most important thing is that they can co-exist as in the above example, and a single TAFReportStatus will not be able to represent the above situation.

![image](https://user-images.githubusercontent.com/30064374/45465998-5e28df80-b74a-11e8-89d8-386c411559e2.png)
![image](https://user-images.githubusercontent.com/30064374/45466017-6c76fb80-b74a-11e8-8a18-ae4962577f4c.png)

A similar issue occurred in METAR/SPECI where MeteorologicalAerodromeReportStatus has values NORMAL, CORRECTION and MISSING but a (content) missing report can be either a normal or corrected one.

![image](https://user-images.githubusercontent.com/30064374/45466064-99c3a980-b74a-11e8-9a48-e3bad4d14a44.png)

May need to introduce a new attribute to hold MISSING and CANCELLATION (the latter for TAF only).  Any suggestion (e.g. ContentStatus)?

**Comment by braeckel** [comment]
This change will also impact the Schematron rules, as I recall there are a number related to NIL and CANCELLATION.

I agree that it is probably best to split apart into a report "status" (AMD, COR) and a separate set of information related to "missing/cancelled/NIL" status.  Note that on METAR/SPECI we currently have an "automatedStation" boolean attribute (for AUTO).  For the missing/cancelled/nil info we have two representational options:

1. Add "cancelled", "nil", "missing", and whatever other boolean fields are required to the appropriate reports as optional attributes.  This would not require any changes to the current "automatedStation" boolean but it may be wise to consider new Schematron rules to ensure that the appropriate co-occurence rules exist for these attributes (for example, if it is an AUTO report it shouldn't also be cancelled)
1. Try to combine AUTO and NIL cases into a single enumeration (for METAR/SPECI) and NIL/CNL (for TAF), I believe this is what you mean by the "contentStatus".  Based on the contents allowed in the template I'm not sure the TAF case makes sense since they have a different set of contents (the END OF TAF IF FORECAST MISSING vs END OF TAF IF FORECAST IS CANCELLED).  We would also need to consider if there are ever cases where NIL and either AUTO or CNL can co-occur.  If there are such cases we could not use a single enumerated attribute to represent both being reported on the same report, since this representation would allow only one or the other option.

Overall I prefer option 1 as it makes it easy to carry the independent fields and I believe it is clearer what is being reported than having another, intermediate "contentStatus" type of attribute.  So I suggest we remove from the current status and add new boolean attributes for each condition, along with new Schematron rules to prevent co-occurrence where necessary.

**Comment by blchoy** [comment]
@mgoberfield please correct me if I am wrong:  MISSING is a concept for bulletin.  During preparation if any of its constituent METAR/TAF reports are not available (i.e. missing), respective NIL messages will be used in place of the reports.  So MISSING and NIL are basically one concept and in my opinion NIL should be preserved as it is part of Annex 3.

I have no strong views on using Boolean or Enumeration for the attributes.  Boolean may be more robust to possible future changes.

**Comment by blchoy** [comment]
After thinking for a while, we may also want to incorporate additional attributes to materialized our wish to reference previous reports as mentioned in #46.

1. Normal report
```
<TAF ReportType="NORMAL">
   ...
</TAF>
```

2. Amendment or correction report (amendment being shown here)
```
<TAF ReportType="AMENDMENT" ReportBacklink="uuid.--UUID_of_report_to_be_amended--">
   ...
</TAF>
```

3. A normal report to cancel previous report
```
<TAF ReportType="NORMAL" ReportCancellation="true" ReportCancellationBacklink="uuid.--UUID_of_report_to_be_cancelled--">
   ... Existing TAC reference to report to be cancelled will be retained
</TAF>
```

4. Amendment or correction report to cancel previous report (correction being shown here)
```
<TAF ReportType="CORRECTION" ReportBacklink="uuid.--UUID_of_report_to_be_amended--" ReportCancellation="true" ReportCancellationBacklink="uuid.--UUID_of_report_to_be_cancelled--">
   ... Existing TAC reference to report to be cancelled will be retained
</TAF>
```

So the case mentioned at the top of this issue, viz "TAF AMD YUDO 161500Z 1600/1618 CNL", should lies with Case 4.

Both ReportBacklink and ReportCancellationBacklink are optional items and in initial implementation I think it is good enough to leave blank.

Views please?

**Comment by mgoberfield** [comment]
So long as these are optional fields for non-routine issuances, I've no objection. So the TAF, SIGMET and AIRMET schemas will drop their elements that reference previous/canceled time periods in favor of the these new attributes using the gml id instead?

**Comment by blchoy** [comment]
In a discussion at the [Google group ](https://groups.google.com/a/wmo.int/forum/#!topic/cbs-avxml-developers/LfDSGyo94H8), Patrick expressed his concern from the producer perspective that the filling up of the backlinks will be costly to implement and it will even be a greater challenge for translation centres.  At the same time, Tero also made a point from the consumer's view point that the backlinks may be able to help locating previous reports.  My gut feeling is that improving references to previous reports is something likely to be welcomed but it is not mature enough to implement right now (even though we only need to introduce two optional attributes).   As there is no urgent need to have backlinks, I will take them out until version 3.1.

**Comment by mgoberfield** [comment]
Certainly it will always remain a challenge for translation centers to make references to previous reports, whether the gml ids, or unique content of the previous report are used as is the case now.  That's why I prefer them to be truly optional and not have schematron rules for them, unless I am overlooking something.

**Comment by blchoy** [comment]
These have been incorporated in 3.0.0RC2.

**Comment by ilkkarinne** [comment]
No need to re-open this old issue, just for documentation: it seems that the ```isNilReport``` attributes mentioned here were never incorporated into the IWXXM 3.0 XML Schemas for TAF, METAR or SPECI.

I could not find the discussion or decision on this in any of the issues in this repository.

**Comment by mgoberfield** [comment]
Did you check TAC-to-XML-Guidance.txt? 

> METAR/SPECI
>  NIL report
>  A NIL report shall be represented by making iwxxm:observation empty with a nilReason of "http://codes.wmo.int/common/nil/missing" 

> TAF
> NIL report
>   A NIL report shall be represented by making iwxxm:baseForecast empty with a nilReason of "http://codes.wmo.int/common/nil/missing" 

Or does this not address your concerns?

**Comment by ilkkarinne** [comment]
Yes @mgoberfield, the guidance is clear in https://github.com/wmo-im/iwxxm/blob/v3.0.0/IWXXM/examples/TAC-to-XML-Guidance.txt, I just added a comment here since the last comments seemed to give a wrong impression on how the missing reports should be encoded in the final IWXXM 3.0.
