### ISSUE TITLE
Improve TAF BECMG time support

### ISSUE THREAD

**Issue by marqh** [wmo-im/iwxxm#13]
In TT-AvXML-4 Mark Oberfield noted that there are two times of interest on a TAF BECMG group: a transition period and a period when the phenomenon exists. Both may need to be represented on TAF, whereas only one is carried today.

"OM_Observation provides a time at which the procedure completed (the result time) and the time or time-period when the result is relevant (the phenomenon time).

The validPeriod defines the period during which this TAF is valid.

TAF HGK 221754Z 2218/2318 18007MPS 4000 BR SCT100

BECMG 2300/2302 NSW CAVOK

What is the phenomenonTime for the BECMG group? Is the TimePeriod two hours long? Or 18 hours from 00Z to 18Z on the 23rd?

If it’s the former (two hours), for a WFS request what forecast will be returned if user request conditions at 06Z on the 23rd for Hong Kong International Airport? If it’s the latter, then how will the two hour duration for the BECMG group be derived? (problem for converting TAF XML->TAC)
​​
To my understanding of phenomenonTime, I believe the latter option is correct.​"

ref; https://software.ecmwf.int/issues/browse/AVXML-32

Created:
    29/Sep/15 9:45 PM 

Reporter:
Aaron Braeckel

**Comment by Tertzoid** [comment]
I think latter intrepetation  is "more" correct.  In your example 
baseForecast phenomenonTime TimePeriod 2218-2302 and changeForecast (BECMG) TimePeriod 2300-2318.  So Periods overlaps 2300-2302.

In example:
http://schemas.wmo.int/iwxxm/2.1/examples/taf-A5-1.xml
FM group looks like right TimePeriod, but BECMG "only" as in TAC.
Hm, maybe not best example, some other mess with times too.
sadly many IWXXM converter implementation uses former intrepetation.

**Comment by braeckel** [comment]
In TT-AvXML 7 it was agreed:
 - The definition of phenomenonTime is a bit stretched and less than ideal for becoming conditions
 - Additional documentation/guidance should be added to the TAF MeteorologicalAerodromeForecastType phenomenonTime to indicate the proper interpretation in these cases

Further, conclusions were that in the long-term:
 - A "derived" set of meteorological conditions in sectional time series was desirable rather than the change indicator approach used today.  This is more consumer friendly in that no work is required to interpret the TAF conditions at any point in time.  This is also easier to generate directly from weather models
 - This TAF reporting change would have implications on data producers and would therefore require METP discussion, and there is not any urgency to work on this
