### ISSUE TITLE
Combine METAR and SPECI product to enable WFS dissemination

### ISSUE THREAD

**Issue by marqh** [wmo-im/iwxxm#15]
At the moment IWXXM includes two separate products for a METAR and SPECI that carry the same information. However, they cannot be disseminated in the same feature type of a WFS because they are two different XML elements. ICAO usage to date has combined METAR and SPECI into a single data stream, and as we move forward that seems likely to continue.

ICAO SWIM, NextGen, and SESAR all use or mention WFS servers for distributing IWXXM data. Therefore this is likely to be a significant issue once modernization activities start deploying WFS services.

Possible solutions:

 1. Remove the SPECI element/product, add a boolean 'specialReport' flag on METAR
 2. Make MeteorologicalAerodromeObservationReport concrete, remove METAR and SPECI elements, and put a mandatory 'specialReport' boolean flag on MeteorologicalAerodromeObservationReport

Both options are confusing because they are changing the way the products are represented as compared to the TAC representations. The correct information is carried but the concept of the METAR and SPECI product types are different.

I have sent a query to the WFS 2.0 group to ensure that my interpretation is correct that both METAR and SPECI cannot be used in the same WFS 2.0 featureType.

Created:
    15/Oct/15 5:00 PM 
Reporter:
    Aaron Braeckel

**Comment by braeckel** [comment]
TT-AvXML-6 decided that it would be good to enable WFS distribution but may raise an issue with AMHS.  Today, much like with TAC, the early content (top-level element in the case of IWXXM) is sufficient to route and sort messages.  If a specialReport flag is set and the product is changed to a METARSPECI product the attribute would need to be examined for communications priority, for example.  However, not adding this is a significant limitation for the likely MET-SWIM use of WFS.

This issue is being raised with WG-MIE.

**Comment by blchoy** [comment]
In addition to communication priority, a SPECI is also different from a METAR report that its reporting is triggered by significant changes in certain observation elements and hence the report time is not as scheduled.  Having said that, if the significant changes occur close to the scheduled report time of a METAR, it will be reported in a METAR instead of a SPECI.

So in short, for an aerodrome providing hourly METAR, you may see:
0100UTC METAR
0130UTC SPECI
0145UTC SPECI
0200UTC METAR

but for an aerodrome reporting half-hourly METAR, it will become:
0100UTC METAR
0130UTC METAR
0145UTC SPECI
0200UTC METAR

Unless ICAO makes a decision to blurred out the distinction of METAR and SPECI, if we want to consolidate the two into a single product, we definitely need to have an identifier for SPECI (like the specialReport flag mentioned by Aaron above) and enforce schematron rules to check SPECI specific requirements as necessary.

**Comment by blchoy** [comment]
With regard to Aaron's concern on AMHS, since all IWXXM messages will have to be encapsulate with COLLECT which includes a WMO AHL, and T1T2 are different for METAR and SPECI,

![image](https://user-images.githubusercontent.com/30064374/33007891-9f64ad9a-ce0b-11e7-8efb-f84a365325c4.png)

There will be no need for AMHS communication systems to reference the METARSPECI product attribute but the COLLECT WMO AHL which is a more generic approach.

> TT-AvXML-6 decided that it would be good to enable WFS distribution but may raise an issue with AMHS. Today, much like with TAC, the early content (top-level element in the case of IWXXM) is sufficient to route and sort messages. If a specialReport flag is set and the product is changed to a METARSPECI product the attribute would need to be examined for communications priority, for example. However, not adding this is a significant limitation for the likely MET-SWIM use of WFS.
>
>This issue is being raised with WG-MIE.

**Comment by braeckel** [comment]
This proposal in general matches with how I've seen it implemented in practice in realtime systems, I've seen several systems where METAR and SPECI reports are combined into a single database so they can be used together as a single product.

To be clear @blchoy, you support having only the METAR element, removing the abstract MeteorologicalAerodromeObservationReport type, and removing SPECI?  In other words there would only be one METAR element for both METAR and SPECI.  

The obvious confusion of this approach is that the TAC codes have two products and IWXXM combines them into only one. Is it appropriate to change the meaning of "METAR" by combining METAR and SPECI?  Or will this confuse IWXXM consumers who miss the new attribute?

A third approach comes to mind: instead of combining everything into METAR as we are discussing we can combine everything into a "METARSPECI" product.  This is a clearer name than MeteorologicalAerodromeObservationReport and skips the confusion regarding IWXXM having a broader use of the word METAR than the TAC codes currently use.  Note that this would completely break backwards compatibility for these two products, unlike Option 1.

Looking at it again fresh I think 'specialIssuance' would be a better term instead of 'specialReport'.

**Comment by blchoy** [comment]
> To be clear @blchoy, you support having only the METAR element, removing the abstract MeteorologicalAerodromeObservationReport type, and removing SPECI? In other words there would only be one METAR element for both METAR and SPECI.
Yes I do.

> The obvious confusion of this approach is that the TAC codes have two products and IWXXM combines them into only one. Is it appropriate to change the meaning of "METAR" by combining METAR and SPECI? Or will this confuse IWXXM consumers who miss the new attribute?
I don't think there will be confusion.  SPECI is merely used to indicate the weather conditions when there is a significant change in one or more of the weather elements.  This is analogous to TAF AMD which will be issued at any time when there is a significant change in the forecast.  As long as the revised IWXXM METAR can accommodate all elements of SPECI and people how to make the TAC <-> IWXXM conversion, it should be fine.

Having said that, I think this should go into a discussion paper for the upcoming WG-MIE meeting for incorporation into Amendment 78.

**Comment by blchoy** [comment]
At the telecon on 26 Apr 2018, it was considered that the issue was related to possible future usage (fetching MET OBS no matter it is a routing or special report) rather than current prevailing usage (fetching separately routing and special reports).  Discussion of this issue is therefore delayed.

**Comment by blchoy** [comment]
> At the telecon on 26 Apr 2018, it was considered that the issue was related to possible future usage (fetching MET OBS no matter it is a routing or special report) rather than current prevailing usage (fetching separately routing and special reports). Discussion of this issue is therefore delayed.

At WG-MIE/7 in 2021, an activity (Activity 3.3) had been set up _"to develop an Aerodrome Observation in IWXXM, incorporating the existing information requirements contained in METAR/SPECI, LOCAL ROUTINE/ LOCALSPECIAL reports and any new requirements from stakeholders"_.  This is in line with our previous thoughts.  Furthermore, as there is no official requests to deal with possible issues for retrieving IWXXM METAR/SPECI with WFS, I am closing this issue.
