### ISSUE TITLE
Update SIGMET CNL rules to leave out VA and TC SIGMETs

### ISSUE THREAD

**Issue by marqh** [wmo-im/iwxxm#18]
The current Schematron rule SIGMET1 implies that SIGMET CNL should be used with VA and TC SIGMETs:

context="//iwxxm:SIGMET|//iwxxm:VolcanicAshSIGMET|//iwxxm:TropicalCycloneSIGMET"

However, Annex 3 does not specify that a CNL SIGMET should include a TC or VA component. For clarity this rule should be updated to just apply against //iwxxm:SIGMET.

This stems from cbs-tt-avxml:576: https://groups.google.com/a/wmo.int/forum/#!topic/cbs-tt-avxml/DtJ8rg2w9Sk.

ref: https://software.ecmwf.int/issues/browse/AVXML-53

    Reporter:
        Aaron Braeckel 

    Created:
        10/Jun/16 6:17 PM

**Comment by marqh** [comment]
B L Choy added a comment - 11/Jul/16 7:05 PM

VolcanicAshSIGMET and TropicalCycloneSIGMET specialized SIGMET, and it is natural for them to also inherit the constraints of SIGMET too (hence the context). Perhaps one need to have constraints in VolcanicAshSIGMET and TropicalCycloneSIGMET to restrict the use of rule SIGMET.SIGMET1?

**Comment by braeckel** [comment]
The first part of the question sparked a discussion in TT-AvXML-6 that led to the creation of issue #46 to add 

Part 2 of the question is regarding States that choose not to follow Annex 3 and should not be reflected in IWXXM.  In Amd 77 Appendix 6 Section 1.1.3 it states: 
"The sequence number referred to in the template in Table A6-1A shall correspond
with the number of SIGMET messages issued for the flight information region (FIR)
since 0001 UTC on the day concerned".  Confusion among sequence numbers is not possible with this approach unless there is a late issuance on May 1 with a sequence number of 1 and an early issuance on May 2 with a sequence number 1.  Fundamentally this is an Annex 3 issue that requires a policy and process solution.
