### ISSUE TITLE
Guidance on R/SNOCLO appears to be incompatible with IWXXM.nilReasonCheck

### ISSUE THREAD

**Issue by lcdunstan** [wmo-im/iwxxm#203]
```
 SNOCLO - Runways closed due to snow
  When all runways are closed due to snow, this shall be indicated with a "runwayState" with a nilReason of "http://codes.wmo.int/bufr4/codeflag/0-20-085/1"
```
but
```
   <sch:pattern id="IWXXM.nilReasonCheck">
      <sch:rule context="//iwxxm:*">
         <sch:assert test="( if( exists(@nilReason) ) then( @nilReason = document('codes.wmo.int-common-nil.rdf')/rdf:RDF/*/skos:member/*/@*[local-name()='about'] ) else( true() ) )">IWXXM.nilReasonCheck: nilReason attributes should be a member of http://codes.wmo.int/common/nil</sch:assert>
      </sch:rule>
   </sch:pattern>
```

so validation fails.

**Comment by mgoberfield** [comment]
Luke,  Good catch. 

All runways closed or all runways cleared (of snow) are treated inconsistently.  For the former condition, nilReason is set in <iwxxm:runwayState>.  For the latter, <iwxxm:runwayState> isn't nilled, but <iwxxm:AerodromeRunwayState> attributes 'allRunways' and 'cleared' are set to 'true'.

**Comment by blchoy** [comment]
I think this is a real issue as we mandate all nilReasons to be a member of code list http://codes.wmo.int/common/nil.  The closest entry I can think of from this code list is http://codes.wmo.int/common/nil/inappropriate but it lacks the direct meaning of snow closure.  In any case this needs at least a patch to fix.

**Comment by porosnie** [comment]
With the new ICAO "global reporting format", which will become applicable in Nov 2020, my understanding was that METAR will no longer be used for providing airport surfaces contamination information. Thus, the current "snowclo" concept would also disappear. If a runway is closed due to snow, it requires anyhow a NOTAM to be published. 

Digital data for runways contamination would be provided through Digital NOTAM, there is a coding scenario being drafted for that using AIXM.

**Comment by blchoy** [comment]
Thanks @porosnie for reminding.  I almost forget this change even though our office are working with the local airport authority on providing such a data automatically.  In the current version of Annex 3:

![image](https://user-images.githubusercontent.com/30064374/73669114-e4e4b080-46e1-11ea-86de-e90fd80a9b8e.png)
where Remark 16 said _"To be included in accordance with 4.8.1.5 b) until 4 November 2020."_

In any case it is still an issue at the moment but because of the time needed to fix we may probably want to propose a way for deprecating rather than fixing this element.

**Comment by blchoy** [comment]
As the applicability of GRF had been delayed for one year in Amendment 80, and so did the removal of runway state in METAR/SPECI, we will implement the use of 'inappropriate' for SNOCLO.  There will be no change to the schema, just the documentations.

**Comment by blchoy** [comment]
This was implemented in IWXXM 2021-2RC1.
