### ISSUE TITLE
Schematron fails Annex 3 abbreviated TEST messages

### ISSUE THREAD

**Issue by mgoberfield** [wmo-im/iwxxm#220]
For TEST SIGMET/AIRMET, and Advisories, the message _can_ 
>  end immediately after the word "TEST"

For advisories, it is immediately after the ADVISORY line. Volcanic Ash Advisory is representative:

![Annotation 2020-05-05 103910](https://user-images.githubusercontent.com/7852621/81079000-eed2a700-8ebc-11ea-8d08-a27f160daff6.png)

However, the schematron rules fault such messages:

![Annotation 2020-05-05 103911](https://user-images.githubusercontent.com/7852621/81079156-2f322500-8ebd-11ea-8212-22632a39214f.png)

Severity: error
Description: VolcanicAshAdvisory.VolcanicAshAdvisory-2: An ordinary report should have appropriately filled elements including Iwxxm:issueTime, iwxxm:issuingVolcanicAshAdvisoryCentre, iwxxm:volcano, iwxxm:stateOrRegion, iwxxm:summitElevation, iwxxm:advisoryNumber, iwxxm:informationSource, iwxxm:eruptionDetails, iwxxm:observation, iwxxm:forecast, iwxxm:remarks and iwxxm:nextAdvisoryTime  Similarily for the Tropical Cyclone and Space Weather advisories as well.

Similar rules exist for SIGMETs and AIRMETs

Severity: error
Description: SIGMET.SIGMET-4: An ordinary report should have appropriately filled elements including Iwxxm:issueTime, iwxxm:issuingAirTrafficServicesUnit, iwxxm:originatingMeteorologicalWatchOffice, iwxxm:issuingAirTrafficServicesRegion, iwxxm:sequenceNumber, iwxxm:validPeriod, iwxxm:phenomenon and iwxxm:analysis. Elements iwxxm:cancelledReportSequenceNumber and iwxxm:cancelledReportValidPeriod shall be absent

**Comment by mgoberfield** [comment]
Please see #221 for one possible resolution.

**Comment by blchoy** [comment]
Thanks @mgoberfield.  I agree that in the tests for ordinary reports there is a missing check on attribute permissibleUsage="OPERATIONAL".  Personally I will not check NON-OPERATIONAL reports no matter it is TEST or EXERCISE as no one will know the sort of TEST or EXERCISE that is going to be conducted.

**Comment by mgoberfield** [comment]
Thanks for the non-sequitur. You are free to decline the pull request.

**Comment by blchoy** [comment]
> Thanks for the opinion. You are free to decline the pull request.

Don't do it yet.  As I will have to implement the change in the model (remember the rules are stored in EA), your suggested changes are essential to double check my work.

**Comment by blchoy** [comment]
Fixed in Version 3.0.1RC1.

The intention is to have more comprehensive integrity check only for OPERATIONAL reports; for NON-OPERATIONAL reports and reports failing translation only minimum amount of elements are expected.  For SIGMET and AIRMET, the mandatory elements for NON-OPERATIONAL reports are less that those indicated in the Annex 3 template to allow for more flexibility in preparing TEST/EXER reports in IWXXM which should be safe as these reports should not be used operationally.

For record purpose, the following rules have been amended:
1. METAR_SPECI.MeteorologicalAerodromeObservationReport-2
2. METAR_SPECI.MeteorologicalAerodromeObservationReport-3
3. METAR_SPECI.MeteorologicalAerodromeObservationReport-4
4. TAF.TAF-2
5. TAF.TAF-3
6. TAF.TAF-4
7. TAF.TAF-5
8. SIGMET.SIGMET-2
9. SIGMET.SIGMET-3
10. SIGMET.SIGMET-4
11. SIGMET.SIGMET-5a (after #208)
12. SIGMET.SIGMET-5b (after #208)
13. SIGMET.SIGMET-6
14. SIGMET.SIGMET-7
15. AIRMET.AIRMET-2
16. AIRMET.AIRMET-3
17. AIRMET.AIRMET-4
18. AIRMET.AIRMET-5a (after #208)
19. AIRMET.AIRMET-5b (after #208)
20. TropicalCycloneAdvisory.TropicalCycloneAdvisory-1
21. TropicalCycloneAdvisory.TropicalCycloneAdvisory-2
22. VolcanicAshAdvisory.VolcanicAshAdvisory-1
23. VolcanicAshAdvisory.VolcanicAshAdvisory-2
24. SpaceWeatherAdvisory.SpaceWeatherAdvisory-1
25. SpaceWeatherAdvisory.SpaceWeatherAdvisory-2
