### ISSUE TITLE
nilReason for METAR and SPECI

### ISSUE THREAD

**Issue by marqh** [wmo-im/iwxxm#23]
Ensure that `nilReason` is a valid entry for METAR and SPECI observed variables.

**Comment by braeckel** [comment]
MIE confirmed that it would like this to be implemented in IWXXM 3 to match WMO 306 despite the fact that this will be implemented at a later date in Annex 3 (probably Amd 79)

**Comment by braeckel** [comment]
This is partly related to #41 and the specification of a minimum set of translated contents. Perhaps Schematron rules can be utilized to ensure that the proper contents are always present in the case of translation failures and translation successes

**Comment by braeckel** [comment]
From #41 the following contents are specified as mandatory: 
METAR (COR) CCCC YYGGggZ (METAR product identification, status, aerodrome identifier, and time)

METAR trend forecasts should not have any (new) nillable information because this a forecast section.  The following observed fields are marked mandatory in Amd 78 which should be made nillable:

 - surface wind
 - visibility
 - cloud
 - air and dewpoint temperature
 - pressure
