### ISSUE TITLE
AIRMET Readiness

### ISSUE THREAD

**Issue by amilan17** [wmo-im/iwxxm#251]
# Branch
https://github.com/wmo-im/iwxxm/tree/FT2021-2_AIRMET

# Summary and Purpose
Validate for public consultation readiness.

# Related Issues
#206 
#241

**Comment by jkorosi** [comment]
I would like to propose change in the documentation of <iwxxm:speedOfMotion/> and <iwxxm:directionOfMotion/>. The TAC-to-XML-Guidance.txt says:

> Movement or expected movement - STNR
  Stationary phenomenon shall be denoted with both iwxxm:directionOfMotion and iwxxm:speedOfMotion absent

but the documentation of these elements says
```xml
<complexType name="AIRMETEvolvingConditionType">
		<complexContent>
			<extension base="gml:AbstractFeatureType">
				<sequence>
					<element name="geometry" type="iwxxm:AirspaceVolumePropertyType">
						<annotation>
							<documentation>The expected geographic region(s) affected by the reported phenomenon at a particular time (thunderstorms, volcanic ash, etc.).  This geometry covers all combinations of phenomenon historically reported in ICAO Annex 3 / WMO No. 49-2: a boundary with a base and top, a TC centre position, and a VA line with a width</documentation>
						</annotation>
					</element>
					<element nillable="true" name="directionOfMotion" type="iwxxm:AngleWithNilReasonType" minOccurs="0" maxOccurs="1">
						<annotation>
							<documentation>The expected direction of movement of a meteorological condition. When no movement is expected, this is a http://www.opengis.net/def/nil/OGC/0/inapplicable nilReason and the speedOfMotion will be 0.  Direction of motion to shall be given in degrees from true North. Plane angle unit of measure (uom) is "deg".</documentation>
						</annotation>
					</element>
					<element name="speedOfMotion" type="gml:SpeedType" minOccurs="0" maxOccurs="1">
						<annotation>
							<documentation>The expected speed of movement of a meteorological condition. When no movement is expected, this will have a value of 0 and directionOfMotion will have a http://www.opengis.net/def/nil/OGC/0/inapplicable nilReason. Speed of movement shall be given in either "km/h" or "[kn_i]" (knot).</documentation>
						</annotation>
					</element>
```
The Manual on codes (306) has to be updated too.

This issue is related to AIRMET as well as SIGMET.

The additional question is: Should this approach be used also for advisories movement? Because it seems that TC ADV follows it, but there is no notice about it in VA ADV. It is not related to SWX ADV.

**Comment by blchoy** [comment]
Thanks for bringing up this inconsistency.

I think what the Guidance said for STNR is WRONG.  The reason is that SIGMET and AIRMET requires either speed+direction of motion OR forecast positions to be present.  If we want to indicate STNR with the absence of speed+direction of motion this will make the representation ambiguous (is the report prepared incorrectly?).  An amendment to the Guidance is necessary.  Of course, the nilReason indicated in the notes is also outdated and this will be amended too.

You also pointed out that speed+direction of motion is also absent too in a TCA if the TC is moving slower than 2km/h.  This is true but this is because there is another mandatory element iwxxm:movement which indicates STATIONARY at the same time so the missing of speed+direction of motion is not ambiguous.

**Comment by jkorosi** [comment]
I agree that the TCA movement is different. I think it is the same approach should be used also for SIGMET/AIRMET and VA ADV.

The reason is that the movement in the ADVISORY is exactly the same movement that is reported in SIGMET. Therefore we should be consistent in reporting. Adding movement type will be also backwards compatible.

**Comment by blchoy** [comment]
> I think it is the same approach should be used also for SIGMET/AIRMET and VA ADV.

Right.  Let's defer this to the next update.

**Comment by blchoy** [comment]
Implementation completed in IWXXM 2021-2RC1.
