### ISSUE TITLE
[question] aixm dependency - incoherencies

### ISSUE THREAD

**Issue by kcris** [wmo-im/iwxxm#277]
Hi,

In general, iwxxm depends on aixm

-------------

I noticed that the new airmet v 3.1 - https://github.com/wmo-im/iwxxm/blob/master/IWXXM/airmet.xsd
uses  `schemaLocation="http://www.aixm.aero/schema/5.1.1/AIXM_Features.xsd"`
Looking at the aixm xsd, I see 
* version 5.1.1 
* copyright 2016, 
* a big AIXM_Features.xsd

-------------

The old airmet v 3.0 - https://github.com/wmo-im/iwxxm/blob/v3.0.0/IWXXM/airmet.xsd
uses `schemaLocation="http://www.aixm.aero/schema/5.1.1_profiles/AIXM_WX/5.1.1b/AIXM_Features.xsd"`
Looking at the aixm xsd I see
* version 5.1.1 = same as above
* copyright 2019 (more recent, even if the iwxxm 3.0 is actually older) - not important though
* a small AIXM_Features.xsd

-------------

So I am totally confused. I see twice aixm 5.1.1, but totally different size/contents (and the wrong dates)
So I am not sure if this is a problem or not for iwxxm users.
What am I missing here? these aixm files are referenced by iwxxm schemas.

Thanks

**Comment by blchoy** [comment]
There used to be a discussion on this topic (#199).  To put the long story short, `http://www.aixm.aero/schema/5.1.1_profiles/AIXM_WX/5.1.1b/AIXM_Features.xsd` is a profile not only containing just some of the features in `http://www.aixm.aero/schema/5.1.1/AIXM_Features.xsd` but a number of these features have also been trimmed down (less elements and/or attributes).

The profile was created after the original schema, that's why it carries a later creation date.

Theoretically this new profile should be given a new namespace instead of `http://www.aixm.aero/schema/5.1.1` but unfortunately due to historical reasons this cannot be done.  That's why we switched back to the full schema to import necessary AIXM features to buy us some time to buy time and pave way for a better solution.

**Comment by kcris** [comment]
thanks a lot, that explains everything.

* The trimmed down profile *without* a new namespace is a bad idea. 
* Fixed now on the xsd side.
* I think using both iwxxm 3,0 and iwxxm 3.1 will still require extra care in the client code since element types that are actually-different (old aixm/wx profile vs full aixm now) are still using the same target namespace (aixm 5.1.1) and same name.

Thank you
