### ISSUE TITLE
Assess whether IWXXM coordinates should be in the Mercator projection

### ISSUE THREAD

**Issue by braeckel** [wmo-im/iwxxm#44]
In TT-AvXML-6 it was mentioned that ICAO policy suggests the use of the Mercator projection in certain cases.  This may imply that IWXXM examples should be in a Mercator projection.  

If so:

 - which datum
 - which dateline
 - other Mercator parameters, if any
 - and therefore; which EPSG code

**Comment by braeckel** [comment]
This is closely related to #52, #53, and #54

**Comment by braeckel** [comment]
This is in the hands of MIE and MOG will handle this.  This is being unassigned from a version until a resolution is sent back to TT-AvXML

**Comment by braeckel** [comment]
In Annex 3, there are notes to the _Advisory message for Volcanic Ash_ and _SIGMET/AIRMET_ which indicate that a line inferred in the message by the joining two points is "a straight line between two points drawn on a map in the Mercator projection or a straight line between two points which crosses lines of longitude at a constant angle".

At ICAO METP MOG2 in 2016, a working paper (SN/16) _Map Projections used for Displaying Volcanic Ash Forecasts: Update of Model VAG and Model SVA of Appendix I to Annex 3_ had specifically pointed out the discrepancies of straight lines prepared on the Mercator projection and displayed on other projections.   The paper further mentioned that "the group may note that the transition to IWXXM and its use of XML/GML geospatial conventions should permit greater flexibility in originating and visualizing such phenomenon since information regarding the projection on which the polygons were generated can be included".

However, in the IWXXM examples for VAA, SIGMET and AIRMET, aixm:horizontalProjection of aixm:AirspaceVolume is either not included or specified incorrectly as http://www.opengis.net/def/crs/EPSG/0/4326.  The correct projection should be http://www.opengis.net/def/crs/EPSG/0/3395.

It is thus necessary to:
1. Amend the examples as necessary
2. Consider mandating the use of aixm:horizontalProjection to describe projection of the geospatial object with schematron rule(s) in IWXXM 3

**Comment by blchoy** [comment]
In WG-MIE/6, Study Note SN/07 - Map Projections raised the concerns in mentioning requirements (e.g. projection) for rendering weather features for end-users as this contradicts with data-centrism in the future SWIM environment where standardised data sets are being used for different applications instead of converting from specific products (e.g. a chart) to meeting the need of other use cases.  The meeting was in general concurrence of describing future weather features in a geodesic way and let applications to render weather features according to their own needs.  Whether there is a need to specify target rendering requirements like projection in IWXXM will be followed up by WG-MIE.  No matter the decision these requirements shall be described by additional attributes to the weather features.

This issue is hereby closed.
