### ISSUE TITLE
Simplify cancellation and NIL cases

### ISSUE THREAD

**Issue by marqh** [wmo-im/iwxxm#8]
The current version of the schemas require a good amount of description for a relatively small message (CNL, NIL, etc.), mostly in the form of OM_Observation information. This should be simplified so that only the necessary information is carried in these cases.

ref: https://software.ecmwf.int/issues/browse/AVXML-17

created:
29/Sep/15 9:10 PM

Reporter:
Aaron Braeckel

**Comment by braeckel** [comment]
Any changes made should also reflect the ICAO WG-MIE/4 decision that was made regarding the minimum set of content that should be included in IWXXM messages.

**Comment by braeckel** [comment]
The original concern about NIL and CNL cases was with the unnecessary structure that was carried by requiring time and location information, which was buried under O&M constructs.  After reviewing all of the current examples it appears that this issue was resolved with #27 changes - there is no longer any unnecessary structure. Closing this issue.
