### ISSUE TITLE
NSC rule in IWXXM 2.1 cannot be applied

### ISSUE THREAD

**Issue by ilkkarinne** [wmo-im/iwxxm#88]
NSC in TAC-to-XML-Guidance.txt:
https://github.com/wmo-im/iwxxm/blob/1543bfe7c526ce8498974f777361d89b958aeb92/2.1.1RC1/TAC-to-XML-Guidance.txt#L19

However, the iwxxm:cloud element may contain xsi:nil="true" attribute (Xerces validator):

> Attribute 'http://www.w3.org/2001/XMLSchema-instance,nil' must not appear on element 'iwxxm:cloud', because the {nillable} property of 'iwxxm:cloud' is false.

**Comment by blchoy** [comment]
I don't understand, as nillable="true" for iwxxm:cloud.

```
<element nillable="true" name="cloud" minOccurs="0" maxOccurs="1">
    <complexType>
        <complexContent>
            <extension base="iwxxm:AerodromeObservedCloudsPropertyType">
                <attribute name="nilReason" type="gml:NilReasonType"/>
            </extension>
        </complexContent>
    </complexType>
</element>
```

**Comment by ilkkarinne** [comment]
Hi @blchoy: I don't know where the quoted element is, but I'm interesting in MeteorologicalAerodromeForecastRecordType at https://github.com/wmo-im/iwxxm/blob/0081cfa8b0d7607f7e50c7fbd5e209d11ecc220e/2.1.1RC1/taf.xsd#L121

**Comment by braeckel** [comment]
As a side note, IWXXM has two different nillable types.  The MeasureTypes (such as airTemperature and verticalVisibility) inherit from MeasureType which have some required information, and in this case we must use xsi:nil to empty the contents due to the MeasureType's structure.  For all other types the nilReason is more "native" and no xsi:nils are required.

I will take a look at the TAC-to-XML-Guidance.txt document and probably remove the "shall be nil" section from that guidance to reduce confusion.

The following validates for me (IWXXM 3):

```xml
<iwxxm:MeteorologicalAerodromeForecast gml:id="uuid.13048235-8f8a-4587-a6be-e8ce99f4525c" cloudAndVisibilityOK="false">
    <iwxxm:phenomenonTime xlink:href="#uuid.ed5d465f-51fb-4ecc-834a-2ee26bb1196f"/>
    <iwxxm:prevailingVisibility uom="m">9000</iwxxm:prevailingVisibility>
    <iwxxm:surfaceWind>
        <iwxxm:AerodromeSurfaceWindForecast variableWindDirection="false">
            <iwxxm:meanWindDirection uom="deg">130</iwxxm:meanWindDirection>
            <iwxxm:meanWindSpeed uom="m/s">5.0</iwxxm:meanWindSpeed>
        </iwxxm:AerodromeSurfaceWindForecast>
    </iwxxm:surfaceWind>
    <iwxxm:cloud nilReason="inapplicable"/>
</iwxxm:MeteorologicalAerodromeForecast>
```
